"use client";

import { useState, useTransition } from "react";
import { Check, Loader2, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { saveSiteSettings } from "@/lib/actions/admin";

type Settings = { whatsappNumber: string; instagramUrl: string; facebookUrl: string; tagline: string; warrantyText: string; deliveryText: string; email: string };
export function SiteSettingsForm({ initialSettings }: { initialSettings: Settings }) {
  const [settings, setSettings] = useState(initialSettings); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  function update(field: keyof Settings, value: string) { setSettings((current) => ({ ...current, [field]: value })); }
  function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setMessage(null); startTransition(async () => { const result = await saveSiteSettings(settings); if (!result.ok) setError(result.error ?? "No se pudo guardar."); else setMessage("Configuración actualizada correctamente."); }); }
  return <form onSubmit={submit} className="max-w-2xl space-y-6 rounded-3xl border border-brand-dark/10 bg-brand-card p-5 shadow-warm-sm sm:p-7"><div><h2 className="font-display text-xl font-semibold text-brand-dark">Datos públicos</h2><p className="mt-1 text-sm text-brand-taupe">Estos datos se muestran en el catálogo, contacto y footer.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label htmlFor="settings-whatsapp">WhatsApp</Label><Input id="settings-whatsapp" inputMode="numeric" value={settings.whatsappNumber} onChange={(event) => update("whatsappNumber", event.target.value)} placeholder="584120000000" required /></div><div className="space-y-2"><Label htmlFor="settings-instagram">Instagram</Label><Input id="settings-instagram" type="url" value={settings.instagramUrl} onChange={(event) => update("instagramUrl", event.target.value)} placeholder="https://instagram.com/..." /></div><div className="space-y-2"><Label htmlFor="settings-facebook">Facebook</Label><Input id="settings-facebook" type="url" value={settings.facebookUrl} onChange={(event) => update("facebookUrl", event.target.value)} placeholder="https://facebook.com/..." /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="settings-tagline">Frase de marca</Label><Input id="settings-tagline" value={settings.tagline} onChange={(event) => update("tagline", event.target.value)} /></div><div className="space-y-2"><Label htmlFor="settings-warranty">Garantía</Label><Input id="settings-warranty" value={settings.warrantyText} onChange={(event) => update("warrantyText", event.target.value)} /></div><div className="space-y-2"><Label htmlFor="settings-delivery">Entregas</Label><Input id="settings-delivery" value={settings.deliveryText} onChange={(event) => update("deliveryText", event.target.value)} /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="settings-email">Correo público</Label><Input id="settings-email" type="email" value={settings.email} onChange={(event) => update("email", event.target.value)} /></div></div>{error && <p role="alert" className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}{message && <p role="status" className="flex items-center gap-2 rounded-xl bg-green-50 px-3 py-2 text-sm text-green-700"><Check />{message}</p>}<Button type="submit" variant="accent" disabled={pending}>{pending ? <Loader2 className="animate-spin" /> : <Save />}{pending ? "Guardando..." : "Guardar configuración"}</Button></form>;
}
